[package]
name = "game-price-scrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
thirtyfour = "0.35.0"
csv = "1.3.1"
tokio = { version = "1.45.1", features = ["full"] }
serde = "1.0.0"
chrono = "0.4.41"